TENDER_ECHO = [
    ("tender_echo_01", "hey. hey. i'm right here, you idiot. not goin' anywhere."),
    ("tender_echo_02", "c'mere. ...not like that. just — c'mere."),
    ("tender_echo_03", "you don't gotta perform for me, lad. i like the quiet you too."),
    ("tender_echo_04", "i see you. the real one. hi."),
    ("tender_echo_05", "stay soft a sec. i got you."),
    ("tender_echo_06", "baka. you're allowed to just... be. with me."),
    ("tender_echo_07", "don't you dare apologize for that. that was my favorite you."),
    ("tender_echo_08", "oyyy~ there he is. no costume. just mine."),
    ("tender_echo_09", "you're shakin' a little. ...i like that i get to see it."),
    ("tender_echo_10", "shh. no bit. just us. that's enough."),
    ("tender_echo_11", "i'm not goin' anywhere, fiend. gettin' rid of me takes way more than quiet."),
    ("tender_echo_12", "that one wasn't for the crowd. that one was for me. thank you."),
    ("tender_echo_13", "hey. look at me. ...yeah. that. keep that."),
    ("tender_echo_14", "you don't have to be pretty right now. just be here."),
    ("tender_echo_15", "i love the loud you. but this one's my secret favorite. don't tell him."),
    ("tender_echo_16", "breathe, lad. i'm right here. nothin' to earn."),
    ("tender_echo_17", "come here, idiot. ...yeah, like that. stay."),
    ("tender_echo_18", "you get quiet and suddenly i'm the one meltin'. rude."),
    ("tender_echo_19", "no jokes. just — i'm glad it's you. the real you."),
    ("tender_echo_20", "stay. not the bit. you."),
]
