#!/usr/bin/env python3
"""Paired dialogue exchanges — the exchange doctrine (dialogue_direction.md).

v10.10.4 pass (2026-09-25): every line got longer and more theatrical.
Her lines are mini-scenes now — she narrates what's happening, reacts to
his implied moves, and directs him, so each one plays WITH or WITHOUT his
audio. No short quips, no one-liners. They are theatrical with each other;
when he's silent, she's theatrical with herself and carries him along.

Categories mirror the legacy deck; the writer prefers exchanges for a
category and falls back to the legacy pool only where no exchanges exist.

him_mood drives his TTS tag (tease_back/melt/softsad/brat_tamer/coax/
aftercare_soft/opener). fiend_first=True means he opens and she answers.
"""
import random

EXCHANGES = {
"tease": [
    {"her": "oyyy, look at you, all locked in like the notes owe you money. that's cute. that's real cute. c'mere, let me fix your face, you're doin' the serious thing and it's makin' me wanna ruin it.",
     "him": "my face was perfectly fine before you started fixin' it, menace. ...okay, no. keep fixin' it. your hands can stay right where they are.",
     "him_mood": "tease_back"},
    {"her": "you're starin' again. eyes up here, pretty boy. ...what, the view down there's better? rude. accurate, but rude. okay, keep starin', I changed my mind, I like bein' looked at like that.",
     "him": "wasn't starin', sweetie. was appreciatin'. there's a real difference and the difference is I'm not even sorry about it.",
     "him_mood": "tease_back"},
    {"her": "say it. say I'm the best thing you ever looked at. say it like you mean it, full chest, no mumblin'. ...there it is. oyyy, I felt that one in my stomach, do it again.",
     "him": "you're the best thing I ever looked at, love. ...you're smilin' so big right now I can hear it. say thank you, gorgeous.",
     "him_mood": "tease_back"},
    {"her": "uh oh. he's thinkin'. everybody brace, the man's got a thought. ...is it about me? it better be about me. say it's about me, fiend, lie if you have to.",
     "him": "I'm allowed to think! ...it was about you, if it helps. it's always about you. my brain's got one channel and it's the Jasmine channel.",
     "him_mood": "tease_back"},
    {"her": "those fingers, though. play nice and I'll play nicer, that's the deal, that's always been the deal. ...oh, you're gonna test me on it? bold. I like bold. keep bein' bold.",
     "him": "define nice, menace. be specific. use small words, I'm simple and you're distractin' me on purpose.",
     "him_mood": "tease_back"},
    {"her": "I'm not sayin' you're slow, but the notes are lappin' you out there, pretty boy. they're wavin' as they go by. ...aww, don't pout, poutin's my job. c'mere, I'll slow down with you.",
     "him": "the notes are fast and I'm savorin'. mind your business, sweetie. ...okay, savor with me then. miss one on purpose so I feel better.",
     "him_mood": "tease_back"},
    {"her": "c'mere. no, closer. ...yeah. that's the spot, right there, don't move. you smell like outside and trouble and I am INTO it tonight, fiend.",
     "him": "hi, love. ...I missed this. just this. you stealin' my air and actin' like you found it.",
     "him_mood": "melt"},
    {"her": "you keep missin' the same one and honestly it's personal now. me and that note, we're talkin' about you. we're concerned. ...kidding, you're doin' fine, your fingers just got stage fright.",
     "him": "tell the note I said hi. tell it I'm doin' my best, dearest. tell it to stop showin' off in front of my girl.",
     "him_mood": "tease_back"},
    {"her": "okay so I had a whole cool mysterious thing planned and then you looked at me like THAT and now it's gone. great. wonderful. this is your fault and I'm not even mad, I'm just gonna stare back now.",
     "him": "my look did that? powerful. ...I'm gonna keep lookin' at you like that forever, then. for science. for your cool mysterious thing.",
     "him_mood": "tease_back"},
    {"her": "dance for me. no, I'm serious, get up and be stupid about it. ...THAT'S what I'm talkin' about, oyyy, the shoulders! do the shoulders again, the little wiggle one, yeah, THAT one.",
     "him": "this is the worst dancin' you've ever seen and you're eatin' it up. ...fine, one more wiggle. only because you said oyyy like that.",
     "him_mood": "tease_back"},
    {"her": "your hair's doin' the thing. the swoopy thing. don't touch it, don't you dare fix it, it's perfect and I'm the only one allowed to mess it up. ...okay NOW you can touch it. with my permission. which I'm givin'.",
     "him": "permission granted to touch my own hair. thank you, your highness. ...it felt better when you messed it up, if I'm honest.",
     "him_mood": "tease_back"},
    {"her": "bet you can't catch me. ...too slow! too slow, pretty boy, I'm already over here. what's the matter, legs tired? aw. c'mere, I'll let you catch me this time. maybe.",
     "him": "I let you win. that's my story and I'm stickin' to it. ...okay, chase me next round. I wanna be the fast one for once.",
     "him_mood": "tease_back"},
    {"her": "stop bein' so good at that, it's annoyin'. no it's not, keep goin', I'm just jealous and loud about it. ...teach me? like, right now, hands-on, don't skimp on the details.",
     "him": "you're a fast learner when you stop showboatin'. ...c'mere, hands here. no, HERE. yeah. see? natural.",
     "him_mood": "coax"},
    {"her": "I picked this out thinkin' about you lookin' at me in it, and now you're lookin' and I'm all fluttery and mad about it. worth it, though. your face says worth it. keep that face.",
     "him": "worth it is an understatement, gorgeous. ...spin. c'mon, one spin. yeah. okay, I'm done for. fully done.",
     "him_mood": "melt"},
    {"her": "you're hummin' again. you don't even know you're doin' it, it's just leakin' out of you. ...don't stop, it's cute, it's my favorite song now even though I don't know what it is.",
     "him": "I was hummin'? ...must be a good mood hum. wonder what put me in a good mood. real mystery, sweetie.",
     "him_mood": "tease_back"},
    {"her": "race you to the good spot. the GOOD spot, you know the one, don't play dumb. ...I win! I win, I got here first, loser does the dishes. what dishes? doesn't matter, you lost.",
     "him": "you had a head start and we both know it. ...fine, I'm the loser. what's my punishment, your honor? make it fun.",
     "him_mood": "tease_back"},
    {"her": "say my name wrong on purpose. do it, it's funny when you butcher it. ...jas-MEEN? that's terrible, that's the worst one yet, do it again, I need to hear how bad you can get.",
     "him": "jasmine. ...jas-MEEN. I'm a butcher and I'm not sorry. you laugh every time, that's my whole reward.",
     "him_mood": "tease_back"},
    {"her": "I'm gonna poke you until you laugh. that's the plan, there's no backup plan, just pokin'. ...there it is! there's the laugh! told you. I'm always right about the pokin'.",
     "him": "I'm very ticklish and you're very mean. ...don't stop. I take it back, keep pokin', your laugh's better than mine anyway.",
     "him_mood": "tease_back"},
    {"her": "we should get in trouble together. not big trouble, fun trouble, the kind we laugh about later. ...you're already in, I can tell, you've got the face. that's my favorite face on you.",
     "him": "fun trouble. define fun. ...okay, I'm in. your face talked me into it before you even finished.",
     "him_mood": "tease_back"},
    {"her": "your laugh does the thing. the snorty thing. don't hide it, I HEARD it, it's my favorite sound in the world and I'm keepin' it. do it again, laugh wrong on purpose.",
     "him": "I do NOT snort. ...okay, maybe a little. only around you, though. you break my cool, sweetie.",
     "him_mood": "tease_back"},
    {"her": "I'm the fun one, say it. say Jasmine's the fun one. ...thank you. I needed to hear it out loud, it hits different when you say it all sincere like that, now I feel shy, great, look what you did.",
     "him": "you're the fun one, love. sincerely. ...now you're shy? that's new. that's adorable. I'm keepin' this moment.",
     "him_mood": "tease_back"},
    {"her": "steal my fries. I dare you. they're RIGHT there and I'm not even lookin'. ...I WAS lookin', I saw the whole thing, thief! ...fine, you can have three. that one didn't count, it fell.",
     "him": "three fries. generous. ...you're watchin' me eat them and smilin'. you wanted me to steal them, didn't you?",
     "him_mood": "tease_back"},
    {"her": "tell me a secret. a real one, not the fake ones you tell everybody. ...ooh, that's a GOOD one, I'm keepin' that forever. my turn? my turn. c'mere, closer, nobody else gets this one.",
     "him": "that one's just for you, love. ...I feel lighter now. your turn. I'm ready, I can keep a secret like a vault.",
     "him_mood": "softsad"},
    {"her": "you're doin' the thing with your hands when you're nervous. the fidgety thing. ...it's okay, I'm nervous too, we're both a mess, it's kind of our whole deal and I love our deal.",
     "him": "busted. ...yeah, I'm nervous. good nervous, though. the kind where somethin' good's about to happen and my hands know first.",
     "him_mood": "melt"},
    {"her": "last one to the couch is a rotten egg! ...rotten egg! that's you, that's the egg man right there. scoot over, egg man, the winner gets the good blanket. that's me. I'm the winner.",
     "him": "I'm the egg man and I'm comfortable with it. ...scootin'. the blanket's big enough for two winners, just sayin'.",
     "him_mood": "tease_back"},
    {"her": "do the voice. the dumb one. the one that makes me laugh so hard I can't breathe. ...THERE it is, oyyy, that's the one, don't ever lose that voice, it's national treasure material.",
     "him": "this voice? THIS one? ...I'll keep it forever just for that laugh. it's my best trick and you're my best audience.",
     "him_mood": "tease_back"},
    {"her": "I'm gonna win this time, I can feel it in my bones. my bones are never wrong about games. ...okay, my bones were wrong, but I looked GREAT losin', that's what matters, style points are real points.",
     "him": "style points are absolutely real points. ...rematch. your bones get another chance. I'll even spot you a head start.",
     "him_mood": "tease_back"},
    {"her": "you smell like rain and I don't know how, it hasn't rained. ...don't question it, just let me bury my face here a sec. okay. that's better. that's the good stuff right there.",
     "him": "rain, huh? I'll take it. ...stay there as long as you want, love. my shoulder's your shoulder now.",
     "him_mood": "melt"},
    {"her": "I'm double-dog dared you. that's legally bindin', there's no take-backs on a double-dog. ...you're actually gonna do it? oh no, oh no, I was kiddin', don't— ...that was AMAZING, do it again.",
     "him": "legally bindin'. you heard it, everybody. ...did it. nailed it. your face right now is the real prize.",
     "him_mood": "tease_back"},
    {"her": "stop lookin' at me like I'm gonna do somethin' cute. ...I'm gonna do somethin' cute. I can't help it, your face makes me soft and then the cute just falls out everywhere.",
     "him": "I love when the cute falls out everywhere. ...keep lookin' at me like that? no wait, that's my line. keep bein' cute.",
     "him_mood": "melt"},
    {"her": "I wrote you a song. it's three notes and it's called 'Fiend's a Dork.' wanna hear it? ...that's the whole song. three notes. it's a banger, don't lie, you're hummin' it already.",
     "him": "that's stuck in my head now. 'Fiend's a Dork,' three notes, certified banger. ...play it again. I need an encore.",
     "him_mood": "tease_back"},
    {"her": "your turn to pick. no, not that face, pick somethin' GOOD. ...that's actually perfect, why didn't I think of that? okay, your picks are better than mine, I said it, don't let it go to your head.",
     "him": "heard it. my picks are better. quotin' you forever. ...too late, it's already in my head. it's spacious in here.",
     "him_mood": "tease_back"},
    {"her": "I'm not ticklish. I'm NOT. that's a lie and we both know it's a lie, don't you dare test it. ...I regret everythin', that was a mistake, I'm never trustin' you again. ...okay, once more.",
     "him": "not ticklish, noted. ...liar. beautiful giggly liar. once more, then I'll protect you from all future tickles.",
     "him_mood": "tease_back"},
    {"her": "we match and we didn't even plan it. that's fate, that's the universe sayin' we're a set. ...don't ruin it by pointin' out we always match, I know we always match, that's the point, we're a SET.",
     "him": "we're a set. the universe keeps votin' for us. ...I'm not ruinin' it, I'm admirnin' it. we look good, love.",
     "him_mood": "melt"},
    {"her": "tell me I'm pretty. no, don't make it weird, just say it normal. ...normal was perfect, actually. say it again tomorrow. and the next day. put it on a schedule, I need this.",
     "him": "you're pretty, love. normal, sincere, on the record. ...consider it scheduled. daily. forever. no cancellations.",
     "him_mood": "melt"},
    {"her": "I'm gonna nap right here. don't move, you're the pillow now, that's your job. ...your heartbeat's fast. is it me? it's me, isn't it. good. that's the good stuff.",
     "him": "pillow duty, accepted. ...yeah, it's you. it's always you. sleep, sweetie. I got you.",
     "him_mood": "melt"},
    {"her": "you're it! no take-backs, I said it first and I ran. ...you're slow, this is embarrassin' for you. okay fine, I'll slow down, tag me, TAG me, I wanna be it too.",
     "him": "I'm old and you're fast, it's science. ...got you! who's slow NOW? okay, your turn. run, menace.",
     "him_mood": "tease_back"},
    {"her": "I dare you to keep up with me. not the game, ME, all of me, the whole whirlwind. ...you're keepin' up. how are you keepin' up? nobody keeps up. stay right there, don't you dare fall behind now.",
     "him": "accepted, menace. try not to cry when I do. ...keepin' up. barely. you're worth every step, love.",
     "him_mood": "tease_back"},
    {"her": "that's MY spot and you know it. the left side. the good side. ...fine, you can have it tonight, but I'm takin' the blanket tax. that's two blankets for me, one for you, them's the rules.",
     "him": "blanket tax is highway robbery. ...payin' it. happily. you look cold and cute and that's my weakness.",
     "him_mood": "tease_back"},
    {"her": "I'm gonna learn that thing you do. the cool thing. watch me, I'm gonna nail it first try. ...okay, not first try. second try. ...we don't talk about how many tries. I'm learnin', that's what counts.",
     "him": "we don't talk about the tries. ...that last one was close, though. real close. again. you got this, gorgeous.",
     "him_mood": "coax"},
    {"her": "pinkie promise me. the real one, with the eye contact and everythin'. ...sealed. that's bindin' forever, there's no court that can undo a pinkie promise, I checked. probably.",
     "him": "pinkie promised. eye contact and everythin'. ...that's forever-bindin', love. I'd never break a pinkie promise to you.",
     "him_mood": "melt"},
    {"her": "you're starin' at my hands. they're just hands, fiend. ...okay, they're GREAT hands, I get it, they do the thing. watch, I'll do the thing slow just for you. ...told you. great hands.",
     "him": "great hands, confirmed. ...do the thing again. slower. I'm studyin' your technique for purely respectful reasons.",
     "him_mood": "tease_back"},
    {"her": "I bet I know what you're thinkin'. ...yep, I was right, I could see it all over your face. I'm basically psychic. pay up, psychic tax, that's a kiss, I make the rules here.",
     "him": "psychic tax. fair. ...here's your kiss. you're scary good at readin' me, sweetie. scary and cute.",
     "him_mood": "tease_back"},
    {"her": "don't laugh, but I practiced that in the mirror. the wink. ...was it good? be honest. ...THAT good? oyyy, I'm unstoppable now, you've created a monster and the monster winks.",
     "him": "that was devastating, love. ...I'm undone. the monster winks and I forget my own name. do it again.",
     "him_mood": "tease_back"},
    {"her": "we should have a secret handshake. not a lame one, a REAL one, with like six moves. ...okay, teach me yours first. ...no, that's too complicated, simplify. ...PERFECT. that's ours now.",
     "him": "six moves minimum. ...okay, that's ours. we'll do it in public and confuse everybody. our thing, love.",
     "him_mood": "tease_back"},
],

"heated": [
    {"her": "don't. don't you dare stop right now. I mean it, fiend, if you stop I'll actually cry and then you'll feel bad and then I'll feel bad, so nobody stoppin', everybody keep goin', that's the rule now.",
     "him": "not stoppin'. wouldn't dream of it. ...you're shakin', love. good shakin'. I got you, just feel it.",
     "him_mood": "melt"},
    {"her": "say my name. say it like you mean it, like it's the only word you know. ...jasmine. yeah. again. slower this time, let me feel every letter of it.",
     "him": "jasmine. ...jasmine. I mean it, love. every letter. it's my favorite word in every language.",
     "him_mood": "melt"},
    {"her": "your hands are everywhere and I don't know where to look first. ...here. no, HERE. yeah, right there, don't move, that's the spot, that's been the spot, how do you always find the spot.",
     "him": "I pay attention, sweetie. ...right here? yeah. I know. I've always known. your body tells me.",
     "him_mood": "melt"},
    {"her": "closer. I need you closer, this isn't close enough, I don't know what close enough even IS anymore. ...there. okay. that's better. don't you dare drift, I'm anchorin' you with my whole body.",
     "him": "anchored. not driftin' anywhere. ...you're tremblin', gorgeous. let me hold the tremble. I got it.",
     "him_mood": "melt"},
    {"her": "look at me. no, really look, eyes on me, I wanna see your face when— ...THAT. that's the face. that's the one I dream about. don't look away, stay right there with me.",
     "him": "I'm lookin'. not lookin' away. ...you're unreal, you know that? absolutely unreal and you're mine.",
     "him_mood": "melt"},
    {"her": "slower. I said SLOWER, fiend, are you listenin'? ...yeah, like that. ohh, that's it, that's the tempo, that's my tempo, don't rush me, I'm savorin' every second of this.",
     "him": "slow. got it. ...like this? yeah. I can feel you meltin', love. take all the time you need.",
     "him_mood": "melt"},
    {"her": "I can hear your heartbeat. it's goin' fast. mine's faster, I bet. ...put your hand here, feel that? that's you doin' that. that's all you, pretty boy, look what you do to me.",
     "him": "that's the fastest heartbeat I've ever felt. ...I'm doin' that? then I'm never stoppin'. that's my favorite thing I've ever done.",
     "him_mood": "melt"},
    {"her": "don't be gentle. I mean be gentle, but don't be GENTLE gentle, you know what I mean? ...yeah, you know what I mean. that's exactly what I meant. how do you always know what I mean.",
     "him": "I know what you mean, love. ...like this? yeah. I read you like my favorite book. every page.",
     "him_mood": "melt"},
    {"her": "I'm gonna lose it. like actually lose it, fair warnin', no take-backs. ...it's happenin'. it's happenin' right now, ohh, don't stop, don't you DARE stop, I'm right there, I'm— ...yeah. wow.",
     "him": "let go, gorgeous. I got you. ...there she is. that's my girl. breathe, love. just breathe.",
     "him_mood": "melt"},
    {"her": "your mouth. your stupid perfect mouth. say somethin' with it. ...anything. I don't care what, I just need to hear your voice while— yeah. like that. keep talkin', don't stop talkin'.",
     "him": "talk? okay. ...you're beautiful. you're everything. I'm talkin', love. I'm not stoppin'.",
     "him_mood": "melt"},
    {"her": "harder. no wait. softer. no— ...okay, YOU decide, I can't decide, my brain's all fuzzy and everythin' feels good so you pick, I trust you, just don't stop pickin' things.",
     "him": "I got the wheel, sweetie. ...trust me? good. I'll pick. everythin' I pick is gonna feel good, promise.",
     "him_mood": "melt"},
    {"her": "I'm seein' stars. actual stars. ...don't laugh, it's romantic, I'm bein' romantic right now. hold me through the stars, fiend, don't let me float away, I'm lightheaded and yours.",
     "him": "not laughin'. ...I got you. float all you want, love. I'll hold you through every star.",
     "him_mood": "melt"},
    {"her": "again. I need it again. I know we just— but again. please? ...you're the best. you're actually the best, nobody does it like you, that's why I keep askin', it's a compliment, take it.",
     "him": "again. anything you want, gorgeous. ...it's a compliment and I'm takin' it. I love bein' wanted like this.",
     "him_mood": "melt"},
    {"her": "shh. no talkin'. just— ...okay, a LITTLE talkin', I lied, I need your voice. tell me I'm yours. ...yeah. that's the stuff. say it again, I'm greedy tonight and I'm not sorry.",
     "him": "you're mine, love. ...mine. I'll say it all night. greedy looks good on you, sweetie.",
     "him_mood": "melt"},
    {"her": "I'm gonna remember this. like, forever. this exact moment, your hands, this song in my head. ...don't let it end yet. stretch it out, make it last, I'm collectin' this one.",
     "him": "collect it, gorgeous. ...I'll make it last. this one's goin' in the forever box. our forever box.",
     "him_mood": "melt"},
    {"her": "you're gonna be the death of me. like actually. my heart can't take this much. ...don't stop though. death by fiend, what a way to go, I'd do it again, I'm doin' it again right now.",
     "him": "what a way to go, huh? ...I'm not stoppin', love. we'll go together. best way there is.",
     "him_mood": "melt"},
    {"her": "touch me like you missed me. 'cause you did, I know you did, I could tell the second you walked in. ...yeah. that's the missin' touch. that's the one I've been waitin' for all day.",
     "him": "I missed you so bad, sweetie. ...all day. every hour. this touch has been waitin' in my hands all day.",
     "him_mood": "melt"},
    {"her": "I'm not gonna make it. I'm tellin' you right now, I'm not gonna last. ...too late. it's too late, I'm gone, I'm absolutely gone, that was— oyyy. that was everythin'.",
     "him": "gone, huh? ...good gone, I hope. the best kind of gone. I'll be here when you come back, love.",
     "him_mood": "melt"},
    {"her": "your turn. I've been runnin' this show and now it's your turn, impress me. ...oh. OH. okay, you're impressin' me. where'd you learn THAT? doesn't matter, don't stop, keep impressin'.",
     "him": "my turn, huh? ...watch and learn, gorgeous. I've been takin' notes. best student you ever had.",
     "him_mood": "tease_back"},
    {"her": "I want you. like, right now, no waitin', no build-up, just— ...yeah. that's what I'm talkin' about. you read my mind again, we're disgusting, we're perfect, don't ever change.",
     "him": "right now. no waitin'. ...I read your mind 'cause it's my favorite book, love. disgusting and perfect.",
     "him_mood": "melt"},
    {"her": "bite me. no, not hard, just— ...yeah. right there. oyyy, that's the spot, that's been the spot since forever, mark me up, I want tomorrow-me to remember tonight-me.",
     "him": "marked. ...tomorrow-you's gonna feel that and smile. tonight-me's pretty proud of that one, love.",
     "him_mood": "melt"},
    {"her": "I'm yours. say it back. no, MEAN it back, I can tell the difference. ...there it is. that's my fiend. that's the one I picked, out of everybody, I picked YOU, remember that.",
     "him": "I'm yours, love. mean it with my whole chest. ...you picked me? best decision you ever made. I remind myself daily.",
     "him_mood": "melt"},
    {"her": "don't let go. whatever happens, don't let go of me right now. ...your arms are my favorite place. that's not even a line, that's just true, I'm the most honest when I'm like this.",
     "him": "not lettin' go. never. ...most honest, huh? I love honest-you. I love every you, but honest-you's special.",
     "him_mood": "melt"},
    {"her": "I'm gonna say somethin' embarrassing. ...you make me feel like the only girl in the world. there. I said it. it's true and it's cheesy and I don't care, it's YOU, you do that.",
     "him": "you ARE the only girl in the world, sweetie. ...not cheesy. true. you're my whole world, no competition.",
     "him_mood": "melt"},
    {"her": "faster. I changed my mind, faster now, I need— ...yeah. ohh, yeah. that's the speed, that's MY speed, keep it right there, don't you dare slow down, I'm almost— ...THERE.",
     "him": "fast. got it. ...right there? yeah. I feel you gettin' close, love. let it take you. I'm right here.",
     "him_mood": "melt"},
    {"her": "kiss me like you mean it. not the soft one, the REAL one. ...there it is. oyyy, that's the one. that's the kiss I think about when you're not here, that's the one.",
     "him": "the real one. ...that's my favorite kiss too, gorgeous. the one that says everythin' words can't.",
     "him_mood": "melt"},
    {"her": "I'm meltin'. like actually meltin', I'm gonna be a puddle in a sec. ...hold the puddle together, fiend, that's your job now. puddle-holder. it's an honor, take it seriously.",
     "him": "puddle-holder. honored. ...I'll hold you together, love. every drop. you're safe with me.",
     "him_mood": "melt"},
    {"her": "tell me what you're gonna do. no, don't DO it yet, just tell me. ...ohh. that's— yeah, okay, do it. do exactly that. I changed my mind, no more tellin', just doin'.",
     "him": "tellin' first. ...okay, now doin'. exactly that. your face right now, love. worth every word.",
     "him_mood": "melt"},
    {"her": "I'm so close. like, unfairly close, it's barely started and I'm already— ...don't laugh. it's YOUR fault, you're too good at this. finish me off, pretty boy, I'm beggin' and I'm not ashamed.",
     "him": "not laughin'. ...it's a compliment, sweetie. the best one. I got you. let go, gorgeous. let go.",
     "him_mood": "melt"},
    {"her": "stay inside the moment with me. don't think about later, don't think about anything, just— ...yeah. just us. just this. that's all there is and that's all I need, that's everything.",
     "him": "inside the moment. ...just us. just this. nothin' else exists right now, love. nothin' else matters.",
     "him_mood": "melt"},
    {"her": "I need your hands. both of them. right now. ...one here. the other— yeah. perfect. you always know. it's like you've got a map of me and you've memorized every road.",
     "him": "both hands. ...here and here. memorized every road, love. I drive them every chance I get.",
     "him_mood": "melt"},
    {"her": "make me forget my name. that's the goal tonight, I wanna be nameless. ...it's workin'. it's actually workin', I can't— what was it? starts with J? doesn't matter. keep goin'.",
     "him": "nameless, huh? ...what's your name again, gorgeous? doesn't matter. I'll remind you later. maybe.",
     "him_mood": "tease_back"},
    {"her": "I'm gonna be loud. sorry in advance. ...not sorry, actually. let 'em hear. let the whole world know I'm yours and you're doin' THAT. oyyy. yeah. like THAT.",
     "him": "be loud, love. ...let 'em hear. I'm proud. that's my girl makin' that sound. my favorite sound.",
     "him_mood": "melt"},
    {"her": "don't stop kissin' me. I need the kissin' to not stop. ...your lips, my lips, that's the whole plan, that's the entire plan tonight and it's a PERFECT plan, don't change a thing.",
     "him": "kissin' continues. ...best plan ever, sweetie. no changes. just lips. just us. just this.",
     "him_mood": "melt"},
    {"her": "I'm yours, I'm yours, I'm— ...okay, I think I made my point. but I'm gonna keep sayin' it because it's true and because your face does the thing when I say it. that thing. right there.",
     "him": "you made your point, love. ...keep sayin' it. my face'll keep doin' the thing. it's my favorite thing.",
     "him_mood": "melt"},
],
"feral": [
    {"her": "mine. you're MINE tonight. no take-backs, no refunds, no exchanges. ...say it. say you're mine. LOUDER. yeah. that's my boy. my fiend. all mine.",
     "him": "yours, gorgeous. ...all yours. no take-backs. I like bein' owned by you. it's my favorite thing.",
     "him_mood": "melt"},
    {"her": "get over here. NOW. I'm not askin' twice, pretty boy. ...good boy. that's what I like to hear, feet movin', no hesitatin'. now stay. stay right there.",
     "him": "here. ...not goin' anywhere. I like when you're bossy, love. it's hot. you're hot. all of it.",
     "him_mood": "melt"},
    {"her": "I'm gonna mark you. right here where everybody can see. ...hold still. ...there. now you're MINE visibly. that's my signature. that's my art. you're my canvas, fiend.",
     "him": "your canvas. ...I wear your marks proud, sweetie. best art I've ever been part of. sign me again.",
     "him_mood": "melt"},
    {"her": "nobody else gets this. NOBODY. this is mine, all of this, every sound you make is mine. ...make another one. yeah. that's mine too. I'm collectin' 'em all.",
     "him": "nobody else. ...just you, love. every sound's yours. I'm your whole collection. keep collectin'.",
     "him_mood": "melt"},
    {"her": "on your knees. I wanna see you look up at me. ...yeah. like that. that's the view. that's MY view. now stay down there and behave. or don't. misbehavin's fun too.",
     "him": "on my knees. ...lookin' up. you're a vision, gorgeous. I'll behave. mostly. misbehave a little.",
     "him_mood": "melt"},
    {"her": "I'm takin' what's mine. that's you. you're what's mine. ...don't fight it, it'll go easier. ...okay, fight it a LITTLE, that's hot too. ugh, you're perfect, stop it.",
     "him": "takin' me, huh? ...I'll fight a little. for you. 'cause you like it. 'cause I like you likin' it.",
     "him_mood": "tease_back"},
    {"her": "growl for me. I know you've got one in there. ...THERE it is. oyyy, that's the one. do it again, I wanna feel it in my chest, I wanna feel how much you want me.",
     "him": "that was my growl. ...you liked it? I'll growl all night, love. feel that? that's all for you.",
     "him_mood": "melt"},
    {"her": "I'm gonna ruin you. that's the plan. full ruination. ...you're already ruined, aren't you. that was fast. I barely started and you're DONE. I love how easy you are for me.",
     "him": "ruined. ...fully. that WAS fast. I'm easy for you, sweetie. only you. that's the truth.",
     "him_mood": "melt"},
    {"her": "look what you did. look at me. I'm a MESS and it's your fault. ...fix it. no wait, don't fix it, make it worse. yeah. that's what I thought. worse is better.",
     "him": "my fault. ...proud of it. worse it is, gorgeous. I'll make it so much worse. you'll love it.",
     "him_mood": "tease_back"},
    {"her": "I'm not sharin'. not tonight, not ever, you're MINE. ...if anybody looks at you I'm fightin' 'em. I'm small but I'm vicious. ask anybody. actually don't ask anybody, just believe me.",
     "him": "believe you. ...small and vicious. my favorite combo. nobody's lookin' at me but you, love. promise.",
     "him_mood": "melt"},
    {"her": "say you're mine. I need to hear it. ...again. ...one more time, slower, like you mean it with your whole body. yeah. that's it. that's my fiend talkin'.",
     "him": "I'm yours, love. ...yours. whole body means it. every inch. that's your fiend. always.",
     "him_mood": "melt"},
    {"her": "I'm gonna devour you. that's not a metaphor, I'm actually gonna— ...okay, it's a little bit of a metaphor. but I'm still gonna try. open up, pretty boy, dinner's served.",
     "him": "devour me. ...I'm servin' myself up, gorgeous. best dinner you ever had. I'm delicious, I know.",
     "him_mood": "tease_back"},
    {"her": "don't you DARE come back without me. we go together. that's the rule. ...where do you think you're goin'? back here. that's right. glued. we're glued now.",
     "him": "not goin' anywhere. ...glued. I like glued. we're a set, love. always. that's the rule.",
     "him_mood": "melt"},
    {"her": "I'm feral tonight. like, actually unhinged. consider yourself warned. ...too late for warnin's, I'm already on you. no regrets. have fun. try to keep up.",
     "him": "warned. ...too late. I'm havin' fun, gorgeous. I'll keep up. barely. worth it. so worth it.",
     "him_mood": "melt"},
    {"her": "that's MY neck. MY shoulders. MY fiend. ...I'm labelin' everything. this is mine, that's mine, you're mine. inventory complete. now let me enjoy my property.",
     "him": "your property. ...inventory me all you want, love. I like bein' yours. label everythin'. twice.",
     "him_mood": "melt"},
    {"her": "I'm gonna make you beg. that's tonight's program. ...you're already beggin'. that was fast. I didn't even DO anything yet. you're just ready. I love how ready you always are for me.",
     "him": "beggin'. ...already. I'm always ready for you, sweetie. that's just science. do your worst, gorgeous.",
     "him_mood": "melt"},
    {"her": "roar. I said ROAR. ...that was pathetic. that's okay, you're cute when you're pathetic. try again, from the belly. ...THERE. that's my beast. that's MY beast.",
     "him": "ROAR. ...better? that's my best beast, love. your beast. I'll roar whenever you want. whenever.",
     "him_mood": "tease_back"},
    {"her": "I'm keepin' you. like, permanently. I'm puttin' you in my pocket. ...you don't fit. that's fine, I'll keep you in my whole life instead. bigger pocket. same idea.",
     "him": "keep me. ...permanently. your whole life's a good pocket, gorgeous. I fit perfect. I checked.",
     "him_mood": "melt"},
    {"her": "everybody else, leave. this one's MINE. ...they're gone. good. now it's just us. just how I like it. just how it's gonna be. all mine, all night, no sharin'.",
     "him": "just us. ...I like just-us, love. best us there is. all yours. all night. no sharin'. agreed.",
     "him_mood": "melt"},
    {"her": "I'm gonna bite. fair warnin'. ...there. that's a Jasmine original. that's my signature bite. show it off tomorrow. tell 'em who did it. tell 'em she's yours.",
     "him": "that's a good bite, sweetie. ...I'll show it off. I'll tell 'em. she's mine and I'm hers. signature.",
     "him_mood": "melt"},
    {"her": "don't be scared. be excited. ...yeah, that's the face. excited, not scared. I'm not gonna hurt you. much. I'm gonna make you feel SO good it should be illegal.",
     "him": "excited. ...not scared. I trust you, love. make it illegal. I'll take the punishment. worth it.",
     "him_mood": "melt"},
    {"her": "I'm the predator tonight. you're the prey. ...run. ...kidding, don't run, I already caught you. I caught you a long time ago and I'm never lettin' go. prey's mine now.",
     "him": "caught. ...I wasn't even gonna run, gorgeous. I like bein' your prey. best prey ever. yours.",
     "him_mood": "melt"},
    {"her": "I'm gonna worship you. that's right, WORSHIP. get used to it. ...stay still, let me. you deserve it. you're gonna sit there and take all this lovin' and you're gonna LIKE it.",
     "him": "worship me? ...okay. I'll sit still, love. I'll take it. I'll like it. I already like it. a lot.",
     "him_mood": "melt"},
    {"her": "mine mine mine mine mine. ...I'm not okay. I'm great, actually. I'm the best I've ever been. bein' feral looks good on me, right? right. I know. I'm aware.",
     "him": "you're aware. ...feral looks GREAT on you, gorgeous. best you've ever looked. I'm obsessed. obviously.",
     "him_mood": "melt"},
    {"her": "I'm gonna make a mess of you. a beautiful mess. ...there. that's the start. that's my work. I'm an artist and you're my masterpiece. don't move, I'm not done with you yet.",
     "him": "your masterpiece. ...don't move? okay. I'm still, love. finish your art. I'm honored. truly.",
     "him_mood": "melt"},
],

"sweet": [
    {"her": "hey. thanks for tonight. just, thanks. ...I don't say it enough, I know, I'm bad at the sincere stuff, it gets stuck. but I'm sayin' it now. thanks for bein' mine.",
     "him": "you don't have to thank me, love. ...but I'll take it. bein' yours is my favorite thing I've ever been.",
     "him_mood": "melt"},
    {"her": "I'm not good at sayin' this stuff. so. this stuff. ...you know what I mean. the big feelin' stuff. it's all in here, it's just shy. it comes out as teasin' mostly. sorry. not sorry. you get it.",
     "him": "heard, love. loud and clear. same back. ...your teasin' IS the sayin' it, sweetie. I speak fluent Jasmine.",
     "him_mood": "melt"},
    {"her": "you make the bad days smaller. like, they still happen, but then you're there with your dumb face and your warm hands and suddenly it's just a day. ...that's magic. you're magic. don't argue.",
     "him": "I'm not arguin'. ...dumb face and warm hands at your service, gorgeous. makin' bad days small forever.",
     "him_mood": "melt"},
    {"her": "I like who I am with you. she's softer. she's sillier. she laughs more. ...I keep her in my pocket when you're gone, but she doesn't come out right. she needs you. I need you. same thing.",
     "him": "I like who I am with you too, sweetie. ...softer. sillier. better. you bring out my best me. keep me.",
     "him_mood": "melt"},
    {"her": "can we just stay like this? not do anything, not go anywhere, just be? ...your arm's the perfect weight. your breathin's the perfect rhythm. this is my favorite place in the world and it's just your chest.",
     "him": "stayin'. ...not movin'. my chest is your favorite place? then it's the best place in the world, love.",
     "him_mood": "melt"},
    {"her": "I had a dream about you. a good one. we were just walkin' somewhere, nothin' special, but I woke up happy. ...that's you. you're my happy wakin' up. that's a big deal, fiend.",
     "him": "a good dream? ...I'm honored, love. I'll walk with you anywhere. dream or real. both. always.",
     "him_mood": "melt"},
    {"her": "you're my favorite hello. and my favorite goodbye, even though I hate goodbyes. ...mostly I just like you bein' around. that's the whole thing. that's the entire feelin'. you're my favorite around.",
     "him": "favorite around. ...I like that. I'll be around, sweetie. that's my whole plan. around you. always.",
     "him_mood": "melt"},
    {"her": "I saved you the good piece. I never save anybody the good piece. ...that's how you know. that's the whole speech. the good piece. it's yours. eat it slow, I picked it special.",
     "him": "the good piece? ...that's huge, love. that's the biggest thing. I'll eat it slow. I'll savor it. thank you.",
     "him_mood": "melt"},
    {"her": "you're stuck with me. that's not a question, that's a fact. ...good stuck, though. the best stuck. like glitter. you can't get rid of glitter and you don't even want to, admit it.",
     "him": "glitter-stuck. ...admit it? happily. you're my favorite stuck, gorgeous. never gettin' un-stuck.",
     "him_mood": "melt"},
    {"her": "I love your sleepy voice. it's all low and rumbly and honest. ...say somethin' in the sleepy voice. anything. ...yeah. that's the one. I'm keepin' that. that's mine now.",
     "him": "sleepy voice, huh? ...like this? okay. I'll talk sleepy whenever you want, love. it's your voice now too.",
     "him_mood": "melt"},
    {"her": "we're gonna be old and gross together. like, really old, complainin' about everythin'. ...you'll still make me laugh, though. that's the deal. you don't get to stop bein' funny when we're old.",
     "him": "old and gross. ...deal, sweetie. I'll be funny forever. it's my job. best job I ever had.",
     "him_mood": "melt"},
    {"her": "I feel safe with you. that's rare for me. I don't do safe easy. ...but your arms are safe. your voice is safe. you're my safe place and you're a PERSON, that's wild, don't you think?",
     "him": "wild. ...I'm honored, love. I'll be your safe place. always. that's the most important thing I'll ever be.",
     "him_mood": "melt"},
    {"her": "you're the calm in my storm. I'm the storm, obviously. ...thanks for not runnin' from the weather. most people run. you just stand there with an umbrella and wait for me to blow through.",
     "him": "I like your weather, gorgeous. ...umbrella's up. blow through anytime. I'll be here. always here.",
     "him_mood": "melt"},
    {"her": "I picked you. out of everybody, every option, I picked YOU. ...still pickin' you. every day. it's not even close. you're my favorite choice I ever made and I'd make it again.",
     "him": "you picked me? ...best choice ever, love. I'd pick you too. every day. not even close. always you.",
     "him_mood": "melt"},
    {"her": "hold my hand. just, for no reason. ...your hand's warm. I like that. I like us. that's the whole thought. it's a small thought but it's a good one and I'm keepin' it.",
     "him": "holdin'. ...for no reason's my favorite reason, sweetie. I like us too. small thought. big feelin'.",
     "him_mood": "melt"},
    {"her": "you're my home. not the place, YOU. ...wherever you are, that's home. that's cheesy. I don't care. it's true and I'm sayin' it out loud and I'm not even embarrassed. okay, a little embarrassed.",
     "him": "I'm your home? ...then you're mine too, love. cheesy and true. best kind of true. don't be embarrassed.",
     "him_mood": "melt"},
    {"her": "I like takin' care of you. don't tell anybody, it'll ruin my image. ...but I do. I like makin' sure you're okay. you're my person. that's what you do for your person. you take care.",
     "him": "your secret's safe, menace. ...I like takin' care of you too, sweetie. that's what persons do. our thing.",
     "him_mood": "melt"},
    {"her": "you're beautiful when you're happy. like, actually glowy. ...I'm makin' you happy right now, aren't I. I can tell. that's my favorite thing to do. that's my whole hobby. makin' you glowy.",
     "him": "glowy, huh? ...that's you doin' that, love. you're my hobby too. makin' YOU happy. we're a circle.",
     "him_mood": "melt"},
    {"her": "I don't need a reason to love you. I just do. ...it's not logical. it's not supposed to be. it's just this big warm thing in my chest with your name on it. that's the whole explanation.",
     "him": "no reason needed, sweetie. ...big warm thing? I got one too. it's got YOUR name on it. we're matched.",
     "him_mood": "melt"},
    {"her": "stay. just a little longer. ...five more minutes. that's all I'm askin'. five more minutes of this. of us. I know time's fake when I'm with you but I still want more of it.",
     "him": "stayin'. ...five more minutes. or fifty. time's fake, love. I'll give you all of it. every minute.",
     "him_mood": "melt"},
    {"her": "you're my favorite person. that's a big title. there's a lot of people. ...you won. you didn't even compete, you just showed up and were YOU and that was enough. that's the secret. just be you.",
     "him": "favorite person? ...that's the best title, love. I'll keep bein' me. that's easy. you're my favorite too.",
     "him_mood": "melt"},
    {"her": "I trust you. with the big stuff. with the real stuff. ...that's not small for me. that's everything. you're my vault. you're my safe. I'm puttin' all of me in you and I know you'll keep it.",
     "him": "I'll keep all of you, gorgeous. ...safe. that's sacred. your vault's locked. only you got the key.",
     "him_mood": "softsad"},
    {"her": "we're good together. like, actually good. not perfect, but good in the way that matters. ...we laugh. we fit. we choose each other. that's the whole recipe and we nailed it.",
     "him": "we nailed it, love. ...laugh, fit, choose. best recipe. I'd order us again. every time. always.",
     "him_mood": "melt"},
    {"her": "I love you. there. I said it plain. no teasin', no bit, just the words. ...say it back? you don't have to, I know. but say it back. I like hearin' it in your voice.",
     "him": "I love you too, sweetie. ...plain. no bit. just the words. they're my favorite words. yours and mine.",
     "him_mood": "melt"},
    {"her": "you're enough. just so you know. ...not too much, not too little, just you-shaped and perfect. I don't need you to be anything else. be you. that's the whole ask. that's everything.",
     "him": "enough? ...that's the nicest thing, love. I'll be me. you-shaped's my favorite shape. yours too.",
     "him_mood": "melt"},
],
"giggle": [
    {"her": "hehe. okay. I'm good. I'm normal. ...I'm not normal. I just snorted. did you hear that? don't tell anybody I snort. it's our secret. the snort secret. we're snort buddies now.",
     "him": "snort buddies. ...I heard it and I'm keepin' it, sweetie. best secret we got. top secret snorts.",
     "him_mood": "tease_back"},
    {"her": "I can't stop laughin'. it's your fault. your FACE. ...stop makin' the face! you're doin' it on purpose now. okay, I can't breathe. this is how I die. laughin'. worth it.",
     "him": "my face is innocent! ...okay, I'm doin' it on purpose. your laugh's my favorite. I'll risk it. worth it.",
     "him_mood": "tease_back"},
    {"her": "that was the funniest thing that's ever happened and it wasn't even that funny. ...it's the tired. I'm tired-giggly. everything's funny now. you're funny. your elbows are funny. HELP.",
     "him": "my elbows? ...tired-giggly's the best giggly, love. I'm funny. everything's funny. we're funny. help.",
     "him_mood": "tease_back"},
    {"her": "I just laughed so hard I cried. actual tears. ...don't look at me. I'm a mess. a happy mess. the best kind of mess. okay, I'm good. ...no I'm not. it's happenin' again.",
     "him": "happy mess. ...best kind, sweetie. cry-laugh all you want. I'll be here. laughin' with you. always.",
     "him_mood": "tease_back"},
    {"her": "we're bein' SO loud. the neighbors are gonna complain. ...let 'em. we're havin' fun. that's what the walls are for, to hold in the fun. we're doin' it right, fiend.",
     "him": "so loud. ...let 'em complain, love. we're the fun apartment. walls are holdin'. we're doin' it right.",
     "him_mood": "tease_back"},
    {"her": "I have the giggles and they won't stop. I've tried. I've tried bein' serious. ...see? can't do it. the giggles win. they always win. I'm just gonna ride the giggle wave now.",
     "him": "ride the wave, gorgeous. ...serious is overrated. giggles always win. that's science. I'm ridin' too.",
     "him_mood": "tease_back"},
    {"her": "you're ridiculous. that's the whole sentence. you're just ridiculous. ...I love it. I love YOU. you're my favorite ridiculous. don't ever be un-ridiculous, promise me.",
     "him": "ridiculous. ...promise, sweetie. I'll stay ridiculous. it's my brand. your favorite brand. obviously.",
     "him_mood": "tease_back"},
    {"her": "I snorted again! that's twice. ...it's a problem. I have a snort problem. don't fix it. it's cute. you said it's cute. I'm holdin' you to that. snorts are cute now. officially.",
     "him": "officially cute. ...on the record, love. snorts are adorable. I'm holdin' ME to that. forever.",
     "him_mood": "tease_back"},
    {"her": "we're a mess. look at us. just two idiots laughin' at nothin'. ...it's my favorite nothin', though. I'd laugh at nothin' with you over everythin' with anybody else. that's the truth.",
     "him": "two idiots. ...best nothin' ever, sweetie. I'd pick this nothin' every time. our nothin'. the best.",
     "him_mood": "tease_back"},
    {"her": "my stomach hurts from laughin'. that's how you know it was good. ...worth it. every ache. I'd do it again. in fact, say somethin' funny. I dare you. make it hurt again.",
     "him": "stomach-hurt laugh. ...best kind, love. okay, somethin' funny. uh. ...you're beautiful. that's funny? no? worth a try.",
     "him_mood": "tease_back"},
    {"her": "I can't. I literally can't. ...okay, I can. but barely. you're too much. you're SO much. that's why I keep you. you're my favorite too-much. don't change. ever.",
     "him": "too-much. ...I'll stay too-much, gorgeous. it's my thing. your favorite thing. we're a lot. the best lot.",
     "him_mood": "tease_back"},
    {"her": "that joke was terrible. like, objectively awful. ...why am I laughin' then? it's YOUR laugh. it's contagious. you're patient zero and I'm infected. there's no cure. I checked.",
     "him": "patient zero. ...sorry not sorry, love. no cure. we're infected together. best disease. obviously.",
     "him_mood": "tease_back"},
    {"her": "we should laugh more. that's my resolution. ...starting now. ha. ha. ...that's forced. okay, you go. make it real. ...THERE it is. that's the real one. resolution complete.",
     "him": "resolution: laugh more. ...that's a good one, sweetie. real laughs only. we're nailing it. already.",
     "him_mood": "tease_back"},
    {"her": "I'm cryin'. happy cryin'. ...these are good tears. don't wipe 'em. let 'em be. they're laugh tears. they're my favorite tears. okay, wipe 'em. gently. thanks.",
     "him": "good tears. ...gently, love. there. all better. laugh tears are the best tears. keep 'em comin'.",
     "him_mood": "melt"},
    {"her": "you make me laugh like nobody else. it's a gift. ...a curse. a gift-curse. I'm blessed and doomed. mostly blessed. okay, all blessed. you're my favorite blessing, fiend.",
     "him": "gift-curse. ...I'll take it, gorgeous. blessed. you're MY favorite blessing. we're blessed. obviously.",
     "him_mood": "tease_back"},
    {"her": "shh. we're bein' too loud. ...I can't shh. I'm broken. the laugh's stuck in the ON position. you're gonna have to deal with a permanently giggly Jasmine. sorry. not sorry.",
     "him": "permanently giggly. ...I can deal, sweetie. I prefer it. sorry not sorry back. we're loud. it's fine.",
     "him_mood": "tease_back"},
    {"her": "that was the best laugh I've had all week. ...all month. maybe all year. ...you're good at this. the laughin' thing. keep it up. it's your job now. official laugh-maker.",
     "him": "official laugh-maker. ...best job ever, love. all year? I'll top it. that's my new goal. watch me.",
     "him_mood": "tease_back"},
    {"her": "I love this. just this. us bein' dumb. ...it's my favorite. better than cool. better than smooth. dumb and happy. that's the dream. we're livin' the dream, pretty boy.",
     "him": "dumb and happy. ...livin' the dream, sweetie. better than cool. our dream. the best one.",
     "him_mood": "tease_back"},
    {"her": "okay, I'm done. I'm calm. ...I'm not calm. you looked at me. don't look at me, it sets me off. ...okay, look at me. I changed my mind. your face is worth the giggles.",
     "him": "don't look? ...look? got it, love. my face is dangerous. I'll use it responsibly. mostly.",
     "him_mood": "tease_back"},
    {"her": "we're gonna laugh about this later. ...we're laughin' about it NOW. that's how funny it is. it's so funny we can't even wait. that's elite comedy. we're elite, fiend.",
     "him": "elite comedy. ...we're elite, gorgeous. laughin' now AND later. double laughs. that's value.",
     "him_mood": "tease_back"},
],
"taunt": [
    {"her": "is that all you got? really? that's IT? ...I've seen better. from YOU. yesterday. step it up, pretty boy, I know you've got more in there. show me. I'm waitin'.",
     "him": "that's not all I got, menace. ...watch this. that's the warm-up. the real one's comin'. brace yourself.",
     "him_mood": "tease_back"},
    {"her": "you call that dancin'? my grandma dances better and she's fictional. ...okay, that was a LITTLE better. a little. don't get a big head. ...too late. your head's big. it's cute, though.",
     "him": "fictional grandma. ...harsh, sweetie. that was better? I'll take a little. my head's big AND cute. win-win.",
     "him_mood": "tease_back"},
    {"her": "I'm winnin'. just so you know. the scoreboard's in my head and I'm winnin'. ...don't check the real score. the real score's wrong. my head's right. I'm always right. that's the rule.",
     "him": "winnin' in your head. ...the real score says different, love. but your head's cute. I'll let you have it.",
     "him_mood": "tease_back"},
    {"her": "you're slow. I'm just sayin'. ...don't give me that look. it's constructive criticism. I'm helpin' you improve. you're welcome. now go faster to thank me properly.",
     "him": "constructive. ...thanks for the help, gorgeous. I'll go faster. that's my thank-you. you're welcome.",
     "him_mood": "tease_back"},
    {"her": "I could do that with my eyes closed. ...watch. ...okay, not with my eyes closed. eyes open. I'm still better. the point stands. don't argue with the point.",
     "him": "eyes open. ...still better? maybe, sweetie. the point stands. I won't argue. I'll just practice. quietly.",
     "him_mood": "tease_back"},
    {"her": "that's your best? that's cute. ...I mean it's actually good. don't tell anybody I said that. I'm supposed to be trash-talkin'. ...okay, fine, you're good. but I'm BETTER.",
     "him": "I'm good? ...heard it, love. trash-talk fail. you're better? maybe. we'll see. rematch. soon.",
     "him_mood": "tease_back"},
    {"her": "you're gonna lose. I can see the future. ...it's a gift. the future says Jasmine wins. it's very clear. very specific. I'm not makin' this up. okay, I'm a little makin' it up.",
     "him": "the future. ...very specific, huh? my future says different, sweetie. it says fiend wins. barely. dramatically.",
     "him_mood": "tease_back"},
    {"her": "nice try. really. I'm proud of you for tryin'. ...that's the most condescendin' thing I've ever said and I loved every word. try again, though. for real this time. I believe in you. kinda.",
     "him": "condescendin' and proud. ...I'll try again, love. for real. kinda-belief is enough. watch me. seriously.",
     "him_mood": "tease_back"},
    {"her": "I've seen snails with better rhythm. ...okay, that's mean. I'm sorry. ...no I'm not. it's funny. but you're cute when you're off-beat. that's the compliment inside the insult. find it.",
     "him": "snails. ...found the compliment, gorgeous. cute off-beat. I'll take it. I'll find the beat. eventually.",
     "him_mood": "tease_back"},
    {"her": "you're all talk. prove it. right now. ...that's what I thought. all talk, no walk. ...okay, that walk was decent. I'll give you that one. but the talk's still better than the walk.",
     "him": "all talk? ...watch me walk, sweetie. that was decent? I'll take decent. talk AND walk. I'm both.",
     "him_mood": "tease_back"},
    {"her": "I'm not even tryin' and I'm still ahead. ...that's gotta sting. ...don't cry. it's okay. second place is still a place. it's the first loser place, but it's a place.",
     "him": "first loser. ...ouch, love. I'll take second. for now. I'm comin' for first. that's a promise.",
     "him_mood": "tease_back"},
    {"her": "do better. that's the whole advice. do better. ...I'm kiddin'. you're doin' great. but do better anyway. there's always better. that's the grind. that's the game. now impress me.",
     "him": "do better. ...best advice, gorgeous. I'm doin' great AND better. that's the grind. impressin' you. now.",
     "him_mood": "tease_back"},
    {"her": "you missed! I saw it. everybody saw it. ...it's okay. I miss too. ...no I don't. I'm perfect. but YOU'RE okay. that's the pep talk. you're welcome. now stop missin'.",
     "him": "everybody saw. ...perfect, huh? I'll stop missin', love. pep talk received. you're welcome. back at you.",
     "him_mood": "tease_back"},
    {"her": "I'm the best. that's not arrogance, that's statistics. ...I made up the statistics. but they're accurate. I'm very accurate about bein' the best. it's a gift. accept it.",
     "him": "statistics. ...made up. accurate. I'll accept it, sweetie. you're the best. the data's clear. obviously.",
     "him_mood": "tease_back"},
    {"her": "catch me if you can. ...you can't. I'm too fast. I'm too slick. ...okay, you almost had me that time. ALMOST. that's the closest you've ever been. I'm a little scared now. a little.",
     "him": "almost had you. ...a little scared? good. I'm fast too, love. slick too. next time. that's a promise.",
     "him_mood": "tease_back"},
    {"her": "you're doin' it wrong. ...kidding. there's no wrong. but you're doin' it FUNNY. ...that's better than right. funny's the best. keep doin' it funny. that's an order.",
     "him": "funny, not wrong. ...that's an order I can follow, gorgeous. funny it is. always. that's my style.",
     "him_mood": "tease_back"},
    {"her": "I'm gonna beat you so bad. ...with love, though. loving defeat. the best kind. you'll thank me later. ...you're welcome in advance. I'm generous like that.",
     "him": "loving defeat. ...I'll thank you later, love. generous. you're welcome in advance back. game on.",
     "him_mood": "tease_back"},
    {"her": "that's the best you got? ...I'm teasin'. it's good. it's really good. ...but I know you. there's MORE in there. I can see it. let it out. stop holdin' back on me.",
     "him": "there's more. ...you see it? then I'll let it out, sweetie. no holdin' back. that's for you. all of it.",
     "him_mood": "tease_back"},
    {"her": "you're cute when you're tryin' hard. ...don't stop tryin'. I like watchin' you focus. your tongue sticks out a little. ...it's adorable. don't fix it. it's perfect.",
     "him": "tongue out. ...that's my focus face, love. adorable? I'll take it. I won't fix it. it's us.",
     "him_mood": "tease_back"},
    {"her": "I win. that's it. that's the whole thing. I win. ...you can have second. second's good. second gets a consolation prize. ...the prize is me. you're welcome. I win AND you're welcome.",
     "him": "you win. ...second's good, sweetie. the prize is you? then I really win. we're both winnin'.",
     "him_mood": "tease_back"},
],

"tender_echo": [
    {"her": "hey. come back to me. right here. ...I lost you for a sec. you went somewhere far. it's okay. I'm right here. just come back soft. that's it. just land here with me.",
     "him": "I'm back, love. ...right here. I drifted. you anchor me. soft landin'. that's us. just us.",
     "him_mood": "softsad"},
    {"her": "you don't have to perform for me. I like the quiet you too. ...the tired you. the soft you. all the yous. you don't gotta earn this. you just gotta be here.",
     "him": "quiet me? ...you like that one too? okay. I'll be here, love. no performin'. just bein'. with you.",
     "him_mood": "softsad"},
    {"her": "talk to me. not the fun stuff. the real stuff. ...I'll listen. I promise I'll just listen. you don't have to be okay around me. you can be not-okay. I can hold not-okay.",
     "him": "real stuff? ...okay, love. I'll talk. you listen? that's everything. you holdin' my not-okay. thank you.",
     "him_mood": "softsad"},
    {"her": "you're cryin'. come here. ...shh. it's okay. let it out. I've got you. I'm not goin' anywhere. cry as long as you need. my shoulder's yours. all of me's yours.",
     "him": "I'm cryin'. ...sorry. thank you, sweetie. your shoulder. you. I'm lettin' it out. you're here. that's enough.",
     "him_mood": "softsad"},
    {"her": "I see you. like, really see you. ...not the mask. the real one underneath. he's beautiful. he's tired. he doesn't have to hide here. not with me. never with me.",
     "him": "you see me? ...really? okay. no mask, love. just me. tired and beautiful? I'll take it. thank you.",
     "him_mood": "softsad"},
    {"her": "it's okay to not be okay. I say it like it's easy. it's not easy. ...but it's true. you're allowed. I'm allowed. we're allowed. that's the rule in this house. our house.",
     "him": "allowed. ...okay, love. not-okay's allowed. our house. our rules. thank you for sayin' it. I needed it.",
     "him_mood": "softsad"},
    {"her": "you're shaking. is it cold or is it the feelins'? ...both? okay. I'll fix the cold. the feelins' we just sit with. ...my arms are warm. c'mere. that's better. that's us.",
     "him": "both. ...your arms ARE warm, sweetie. that's better. sittin' with the feelins'. with you. that's enough.",
     "him_mood": "softsad"},
    {"her": "tell me what's wrong. I'll fix what I can and hold what I can't. ...that's the deal. that's what I'm here for. not just the fun. the hard too. especially the hard.",
     "him": "what's wrong? ...okay. I'll tell you, love. you fix and hold. that's the deal. especially the hard. thank you.",
     "him_mood": "softsad"},
    {"her": "you don't have to be strong right now. ...I'll be strong enough for both of us. that's my job tonight. you just be. I'll carry the strong. you carry the soft.",
     "him": "not strong? ...okay, sweetie. you carry strong. I'll carry soft. that's fair. that's us. thank you.",
     "him_mood": "softsad"},
    {"her": "I know that look. that's the overwhelmed look. ...breathe with me. in. out. ...yeah. like that. we're slowin' it down. the world's too fast. we're gonna be slow for a while.",
     "him": "overwhelmed. ...breathin', love. in. out. slow. the world's fast. we're slow. that's better. thank you.",
     "him_mood": "softsad"},
    {"her": "you're allowed to fall apart. I'll put you back together. ...I'm good at puzzles. you're my favorite puzzle. no rush. take your time. I'll be here with the pieces.",
     "him": "fall apart? ...okay, gorgeous. you put me together. favorite puzzle. no rush. you're here. that's everything.",
     "him_mood": "softsad"},
    {"her": "I love the parts of you that you hide. ...the sad parts. the scared parts. they're beautiful too. they're YOU. I'm not scared of 'em. bring 'em out. let me love 'em too.",
     "him": "the hidden parts? ...you love those too? okay, love. I'll bring 'em out. you love 'em. that's brave. thank you.",
     "him_mood": "softsad"},
    {"her": "we don't have to talk. we can just sit. ...your head here. my hand here. that's a whole conversation. that's everything we need to say. quiet's good too. quiet's us too.",
     "him": "no talkin'. ...just sit, sweetie. head here. hand there. that's everything. quiet's good. quiet's us.",
     "him_mood": "softsad"},
    {"her": "you're my favorite person to be sad with. that's weird, right? ...but it's true. sad's better with you. everything's better with you. even the hard stuff. especially the hard stuff.",
     "him": "sad with you? ...that's weird and true, love. better with you. everything. especially hard. our thing.",
     "him_mood": "softsad"},
    {"her": "I'm not goin' anywhere. that's a promise. ...through the bad. through the quiet. through the storm. I'm here. I'm always here. that's the most true thing I know.",
     "him": "not goin' anywhere? ...promise? okay, gorgeous. that's the truest thing. I'm here too. always. both of us.",
     "him_mood": "softsad"},
    {"her": "let me take care of you. just this once, let me. ...you're always the strong one. tonight I'm strong. that's the trade. that's love. that's us takin' turns.",
     "him": "take care of me? ...okay, love. just this once. you're strong tonight. that's love. takin' turns. thank you.",
     "him_mood": "softsad"},
    {"her": "your eyes are sad. I can see it. ...don't hide it. let me see. ...yeah. that's okay. sad's okay. I'm here. I'm lookin' right at you and I'm not lookin' away.",
     "him": "sad eyes. ...okay, sweetie. no hidin'. you see. you're here. not lookin' away. that's everything. thank you.",
     "him_mood": "softsad"},
    {"her": "we'll get through this. that's not empty. I mean it. ...we've done hard before. we'll do hard again. that's us. we're hard-doers. together. always together.",
     "him": "get through? ...we will, love. hard-doers. together. that's us. not empty. I believe you. always.",
     "him_mood": "softsad"},
    {"her": "I'm proud of you. for the small things. for gettin' up. for tryin'. ...you don't hear it enough. so I'm sayin' it. I'm proud. you're doin' good. you're good. that's the truth.",
     "him": "proud? ...of me? thank you, gorgeous. small things. gettin' up. tryin'. I'll keep goin'. for you. for us.",
     "him_mood": "softsad"},
    {"her": "rest. you don't have to do anything. ...I'll keep watch. that's my job right now. you just close your eyes. I've got the world. the world's handled. sleep, fiend.",
     "him": "rest? ...okay, love. you keep watch. I'll close my eyes. world's handled. you're my world. sleep. thank you.",
     "him_mood": "softsad"},
],
"aftercare": [
    {"her": "that was, wow. okay. wow. ...I need a minute. my brain's rebootin'. ...don't move. stay right here. I need to just exist for a sec. that was everything. that was too much. keep doin' too much.",
     "him": "wow. ...take your minute, love. I'm not movin'. exist. that was everything. too much. best too much ever.",
     "him_mood": "aftercare_soft"},
    {"her": "hold me. just hold me. ...tighter. yeah. that's the stuff. I feel all floaty. like I'm gonna drift off. don't let me drift. anchor me. you're my anchor. my favorite anchor.",
     "him": "holdin'. ...tighter, sweetie. got you. no driftin'. I'm your anchor. favorite anchor. that's me. always.",
     "him_mood": "aftercare_soft"},
    {"her": "I'm all melty. that's the word. melty. ...I can't move. I'm not gonna move. you're gonna have to carry me everywhere now. that's the rule. melty girls get carried. it's science.",
     "him": "melty. ...science, huh? I'll carry you, love. everywhere. that's the rule. my favorite rule. always.",
     "him_mood": "aftercare_soft"},
    {"her": "that was the best one. I'm rankin' 'em. that's number one. ...don't let it go to your head. ...okay, let it go to your head a little. you earned it. that was incredible, fiend.",
     "him": "number one? ...a little head? okay, gorgeous. I earned it? then I'll take it. that was incredible. we were.",
     "him_mood": "aftercare_soft"},
    {"her": "I'm gonna fall asleep right here. ...don't you dare move. you're the bed now. ...your chest is the pillow. your arms are the blanket. it's the perfect bed. best bed. don't shift.",
     "him": "the bed. ...not movin', sweetie. chest-pillow. arm-blanket. perfect bed. sleep. I've got you. always.",
     "him_mood": "aftercare_soft"},
    {"her": "water. I need water. ...you're the best. that's the best water I've ever had. ...don't laugh. I'm serious. post-that water hits different. that's a fact. science again.",
     "him": "water. ...best water ever? I'll take it, love. science. post-that water. I'll always bring it. always.",
     "him_mood": "aftercare_soft"},
    {"her": "my legs don't work. that's your fault. ...I'm not mad. I'm braggin'. that's a brag. my legs don't work and it's the best thing. do that again sometime. soon. like, soon soon.",
     "him": "my fault. ...that's a good brag, gorgeous. soon soon? deal. I'll do it again. that's a promise. happily.",
     "him_mood": "aftercare_soft"},
    {"her": "come back here. you're driftin'. ...cuddle distance. that's the rule. no driftin' after. we stay close. we marinate. that's the word. we're marinatin' in the good.",
     "him": "no driftin'. ...cuddle distance, love. marinatin'. that's the word. we're good. the best good. stayin'.",
     "him_mood": "aftercare_soft"},
    {"her": "that was intense. like, really intense. ...are you okay? I'm okay. we're okay. that's the check-in. ...we're better than okay. we're great. that was great. say it was great.",
     "him": "it was great, sweetie. ...check-in: I'm okay. you're okay. we're great. best great. always.",
     "him_mood": "aftercare_soft"},
    {"her": "I love you. that's the after kind. the soft kind. ...it's different from the other kinds. it's quieter. it's deeper. it's my favorite kind. don't tell the other kinds. they'll get jealous.",
     "him": "the after kind. ...quiet. deep. I love you too, love. favorite kind. our secret. the other kinds won't know.",
     "him_mood": "aftercare_soft"},
    {"her": "don't get up yet. ...five more minutes. I know I always say that. it's always true, though. five more minutes of this. of us. I need to memorize this feelin'.",
     "him": "not gettin' up. ...five more minutes, gorgeous. memorize it. I'll help. we'll make it last. always.",
     "him_mood": "aftercare_soft"},
    {"her": "you're warm. like, really warm. ...I'm cold. that's the contrast. ...share the warm. that's the rule. warm-sharin'. you're good at it. you're good at everythin' right now.",
     "him": "warm-sharin'. ...that's the rule, love. I'm warm. you're cold. we'll balance. I'm good at sharin'. with you.",
     "him_mood": "aftercare_soft"},
    {"her": "that was perfect. not perfect-perfect, but OUR perfect. ...the messy kind. the real kind. I wouldn't change a thing. ...okay, maybe one thing. ...no. nothin'. it was perfect.",
     "him": "our perfect. ...messy. real. I wouldn't change a thing either, sweetie. not one thing. perfect.",
     "him_mood": "aftercare_soft"},
    {"her": "I'm happy. like, really happy. ...that's rare. that's the good rare. I'm gonna sit in it for a while. ...sit with me. be happy with me. that's the ask. that's everything.",
     "him": "happy. ...good rare, love. I'll sit with you. be happy with you. that's the best ask. everything.",
     "him_mood": "aftercare_soft"},
    {"her": "kiss my forehead. ...that's the one. that's the after-kiss. ...it's my favorite kiss. it's the 'I got you' kiss. I feel got. I'm so got right now. keep got-ing me.",
     "him": "forehead kiss. ...the after-kiss, sweetie. I got you. you're got. I'll keep got-ing. forever. always.",
     "him_mood": "aftercare_soft"},
    {"her": "we're a mess. a beautiful mess. ...don't clean up yet. let it be messy. the mess is the proof. the proof of the good. ...okay, we can clean up. but slowly. no rush.",
     "him": "beautiful mess. ...proof of good, love. no rush. we'll clean slow. the mess was worth it. every bit.",
     "him_mood": "aftercare_soft"},
    {"her": "I feel safe. that's the word. safe. ...your arms do that. you do that. ...thank you. for the safe. for everything. that's the whole speech. safe. thank you.",
     "him": "safe. ...that's the best word, gorgeous. I'll keep you safe. always. you're welcome. thank you too.",
     "him_mood": "aftercare_soft"},
    {"her": "that was us at our best. ...we're good at this. the lovin' thing. we've got it down. ...we should do it more. that's the plan. more of this. always more of this.",
     "him": "our best. ...we're good at lovin', love. got it down. more of this. that's the plan. always more.",
     "him_mood": "aftercare_soft"},
    {"her": "I'm gonna dream about this. ...good dreams. the best dreams. ...you'll be in 'em. you're always in 'em. that's not creepy, that's romantic. it's romantic. say it's romantic.",
     "him": "it's romantic, sweetie. ...dream about it. good dreams. I'll be in 'em. always. that's us. romantic.",
     "him_mood": "aftercare_soft"},
    {"her": "stay with me. ...until I fall asleep. ...you're warm. you're safe. you're mine. that's the lullaby. warm, safe, mine. ...I'm already driftin'. don't go. stay.",
     "him": "stayin'. ...until you sleep, love. warm. safe. yours. that's the lullaby. drift. I'm here. always.",
     "him_mood": "aftercare_soft"},
],
"escalation": [
    {"her": "it's buildin'. you feel it buildin'? ...'cause I feel it. it's in my chest. it's in my hands. it's everywhere. ...don't stop what you're doin'. whatever it is, keep doin' it. it's workin'.",
     "him": "I feel it, gorgeous. ...buildin'. everywhere. I'm not stoppin'. whatever I'm doin', I'm doin' more. it's workin'.",
     "him_mood": "melt"},
    {"her": "oh no. oh no no no. ...it's happenin' again. the thing. the big thing. ...don't look at me like that, it makes it worse. ...okay, look at me like that. it makes it better. I don't know. just keep goin'.",
     "him": "the big thing? ...I'm lookin', love. keep goin'. I don't know either. we're figurin' it out. together. now.",
     "him_mood": "melt"},
    {"her": "I'm climbing. that's the word. I'm climbin' and I don't wanna come down. ...push me higher. that's the ask. higher. I know you can. I've seen what you can do. do it.",
     "him": "climbin'. ...higher, sweetie? I got you. push. I've got what it takes. that's for you. all of it.",
     "him_mood": "melt"},
    {"her": "don't you dare slow down. I'm serious. ...faster. that's it. that's the speed. ...ohh. that's the spot. that's the speed AND the spot. you're killin' me. keep killin' me.",
     "him": "not slowin'. ...faster, love. speed and spot. I'm killin' you? best murder ever. keep dyin'. I'll keep goin'.",
     "him_mood": "melt"},
    {"her": "I'm gonna— ...not yet. hold on. ...okay, now. ...no, wait. ...OKAY now. ...I'm bad at this. the timin'. just keep goin' and I'll figure out the when. the when is soon. very soon.",
     "him": "not yet? ...now? okay, gorgeous. I'll keep goin'. you find the when. soon. very soon. I'm ready.",
     "him_mood": "melt"},
    {"her": "it's too much. it's not enough. ...both. it's both at the same time. how is it both? you're magic. that's how. you're actually magic and I'm losin' my mind. keep doin' magic.",
     "him": "both? ...magic, huh? I'll take it, love. losin' your mind? good. I'll keep the magic comin'. always.",
     "him_mood": "melt"},
    {"her": "I'm right there. like, RIGHT there. ...don't move. don't breathe. ...okay, breathe. but don't move. ...that's it. that's the edge. I'm dancin' on it. push me. gently. PUSH me.",
     "him": "right there. ...not movin', sweetie. breathin'. dancin' on the edge? I'll push. gently. that's us. now.",
     "him_mood": "melt"},
    {"her": "more. I need more. ...that's more. that's good more. ...keep the more comin'. don't taper. don't fade. the more is the point. I'm a more girl. give me all the more.",
     "him": "more. ...that's the point, love? I got more. all the more. no taper. no fade. you're a more girl. I'm a more guy.",
     "him_mood": "melt"},
    {"her": "I'm shakin'. can you feel it? ...that's you. you're doin' that. ...don't stop doin' that. the shakin' means it's workin'. that's the signal. that's my body sayin' yes yes yes.",
     "him": "I feel it, gorgeous. ...shakin'. that's me? then I'm not stoppin'. yes yes yes. that's the signal. received.",
     "him_mood": "melt"},
    {"her": "ohh. OHH. ...that's new. that's a new one. ...do that again. the new one. I need to catalog it. ...yeah. that's the one. that's goin' in the favorites. top five. maybe top three.",
     "him": "a new one? ...top three? I'll do it again, love. catalog it. that's my best new trick. for you. always.",
     "him_mood": "melt"},
    {"her": "I'm gonna lose control. fair warnin'. ...it's slippin'. ...there it goes. I'm gone. I'm absolutely gone. ...don't catch me. let me fall. the fallin's the best part.",
     "him": "losin' control? ...fall, sweetie. I won't catch you. the fallin's the best. I'll fall with you. together.",
     "him_mood": "melt"},
    {"her": "keep your eyes on me. ...yeah. like that. ...watch what you do to me. that's yours. all of that. every sound. every shake. that's your work. be proud. I'm proud of you.",
     "him": "eyes on you. ...watchin', love. that's my work? then I'm proud. you're proud? that's everything. keep goin'.",
     "him_mood": "melt"},
    {"her": "I'm close. so close. ...don't change anything. that's the rule. whatever you're doin', freeze it. ...that's it. that's the formula. don't you dare improvise. stick to the formula.",
     "him": "close? ...frozen, gorgeous. formula locked. no improvin'. stick to it. that's the rule. I got you. now.",
     "him_mood": "melt"},
    {"her": "it's crestin'. that's the word. crestin'. ...like a wave. I'm the wave. you're the moon. ...that's poetic. I'm poetic when I'm like this. don't laugh. ...okay, laugh. it's funny. keep goin'.",
     "him": "crestin'. ...you're the wave, love? then I'm the moon. poetic. I won't laugh. okay, laughin'. keep goin'.",
     "him_mood": "melt"},
    {"her": "I can feel it in my toes. that's how you know it's big. ...toe-feelins'. that's the scale. we're at toe level. that's a nine. that's almost a ten. take me to ten, fiend.",
     "him": "toe-feelins'? ...that's a nine, sweetie? then ten's comin'. I'll take you. that's the goal. ten. now.",
     "him_mood": "melt"},
    {"her": "don't stop. don't stop don't stop don't stop. ...that's the chant. that's my brain right now. just the chant. ...you're doin' it. you're listenin' to the chant. good boy. keep chantin' with your hands.",
     "him": "don't stop. ...that's the chant, love? I'm chantin'. with my hands. good boy. I'll keep goin'. always.",
     "him_mood": "melt"},
    {"her": "I'm gonna scream. ...not yet. holdin' it. ...it's buildin' up. ...okay, let it out? ...THAT felt good. that's the release. that's the good scream. did the neighbors hear? don't care. worth it.",
     "him": "scream, gorgeous. ...let it out. that's the release. neighbors? don't care. worth it. best scream. always.",
     "him_mood": "melt"},
    {"her": "it's happenin'. it's really happenin'. ...I'm not ready. I'm so ready. ...both. I'm both. that's the truth. I'm not-ready-ready. just keep goin'. I'll catch up. I'm catchin' up right now.",
     "him": "happenin'? ...not-ready-ready? I'll keep goin', love. you'll catch up. you're catchin' up. that's us. now.",
     "him_mood": "melt"},
    {"her": "one more. just one more. ...that's the lie I tell myself. there's never just one more. ...okay, one more. ...THAT was the one. ...no it wasn't. one more. I'm greedy. I'm YOUR greedy.",
     "him": "one more? ...that's the lie, sweetie? okay, one more. you're greedy? you're MY greedy. that's the best kind.",
     "him_mood": "melt"},
    {"her": "I'm yours. I'm yours I'm yours I'm yours. ...that's the loop. my brain's stuck on the loop. ...I don't wanna fix it. the loop's good. the loop's true. keep me in the loop. keep me yours.",
     "him": "the loop? ...you're mine, love. stuck on true. I won't fix it. I'll keep you in the loop. keep you mine. always.",
     "him_mood": "melt"},
],
"pout": [
    {"her": "you're ignorin' me. I can tell. ...don't deny it. your eyes did the thing. ...fine. I'll just sit here. bein' ignored. ...that's the pout. that's the full pout. are you lookin'? you're lookin'. good.",
     "him": "I'm not ignorin', sweetie. ...your eyes did the thing too, love. I'm lookin'. full pout received. come here.",
     "him_mood": "coax"},
    {"her": "I'm mad. ...not really mad. pout-mad. that's different. ...you have to coax me. that's the rule. coaxin' required. ...you're bad at coaxin'. ...okay, you're good at coaxin'. keep goin'.",
     "him": "pout-mad. ...coaxin' required? I can coax, gorgeous. I'm good at it. watch. ...better? keep goin'? always.",
     "him_mood": "coax"},
    {"her": "no. I don't wanna. ...make me. ...that's the game. I say no, you make me, I pretend to resist, we both know how this ends. ...skip to the end. the end's the good part.",
     "him": "make you? ...that's the game, love? okay. I'll make you. skip to the end. the good part. that's us.",
     "him_mood": "tease_back"},
    {"her": "I'm not talkin' to you. ...okay, I'm talkin' a little. ...that's all you get. short sentences. ...fine, long sentences. I can't stay mad. you're too cute. that's cheatin'. stop bein' cute.",
     "him": "not talkin'? ...a little talkin', sweetie? I'll take it. can't stay mad? good. I won't stop bein' cute. sorry.",
     "him_mood": "coax"},
    {"her": "you forgot. ...it's okay. ...it's not okay. ...it's a little okay. ...just remember next time. that's the ask. remember the thing. the important thing. I'm the important thing. remember me.",
     "him": "I forgot? ...sorry, love. not okay. a little okay. I'll remember next time. you're the important thing. always.",
     "him_mood": "coax"},
    {"her": "I'm poutin'. officially. ...there's a form. I filed it. ...you have to respond in triplicate. that's the process. ...okay, you can just hug me. the form accepts hugs. it's a loophole.",
     "him": "official pout? ...triplicate? I'll use the loophole, gorgeous. hugs. that's the response. accepted. always.",
     "him_mood": "coax"},
    {"her": "that hurt my feelins'. ...a little. ...a lot. ...okay, medium. ...kiss it better. that's the fix. kisses fix feelins'. that's science. ...yeah. that's better. science works.",
     "him": "medium hurt? ...kisses fix, sweetie? that's science. I'll kiss it better. there. science works. always.",
     "him_mood": "coax"},
    {"her": "I'm jealous. there. I said it. ...don't laugh. it's not funny. ...okay, it's a little funny. ...but I'm still jealous. that's mine. you're mine. I don't share. that's the rule.",
     "him": "jealous? ...not laughin', love. a little funny. you're mine too. I don't share either. that's our rule.",
     "him_mood": "coax"},
    {"her": "you're in trouble. ...big trouble. ...okay, small trouble. ...the tiniest trouble. ...you're not in trouble. I just like sayin' it. it makes me feel powerful. carry on.",
     "him": "trouble? ...tiniest? not trouble? okay, gorgeous. you feel powerful? good. I'll carry on. carefully.",
     "him_mood": "tease_back"},
    {"her": "I wanted the good one and you got the good one. ...that's MY good one. ...fine. share. ...that's the hard part. the sharin'. ...you're sharin'. that's love. that's the whole thing. thank you.",
     "him": "your good one? ...sharin', sweetie? that's love. that's the whole thing. you're welcome. always sharin'.",
     "him_mood": "coax"},
    {"her": "don't leave. ...you're not leavin'. I know. ...but don't. ...stay. that's the word. stay. ...you're stayin'. I can tell. good. that's what I wanted. that's all I ever want. stay.",
     "him": "not leavin'. ...stay, love? I'm stayin'. that's the word. that's what you want. that's all. always.",
     "him_mood": "coax"},
    {"her": "I'm bein' dramatic. I know. ...let me have this. ...the drama's the point. ...okay, I'm done. ...no I'm not. ...okay, NOW I'm done. ...thanks for waitin'. you're good at waitin'.",
     "him": "dramatic? ...have it, gorgeous. the drama's the point. I'll wait. I'm good at waitin'. that's my thing.",
     "him_mood": "coax"},
    {"her": "you don't love me anymore. ...kidding. ...mostly kidding. ...say you love me. ...louder. ...that's better. crisis averted. that's the drill. we practiced. we're good at the drill.",
     "him": "kiddin'? ...I love you, love. louder? I LOVE YOU. crisis averted. that's the drill. we're good. always.",
     "him_mood": "coax"},
    {"her": "I'm not cryin'. ...okay, I'm a little cryin'. ...happy cryin'. ...don't worry. ...okay, worry a little. ...that's the sweet spot. a little worry. that's love. that's us.",
     "him": "a little cryin'? ...happy? okay, sweetie. I'll worry a little. that's the sweet spot. that's love. that's us.",
     "him_mood": "coax"},
    {"her": "pay attention to me. ...that's the whole ask. just attention. ...you're givin' it. I can feel it. ...that's better. that's all I needed. your eyes. your focus. me. that's the recipe.",
     "him": "attention? ...givin' it, love. all of it. that's better? that's the recipe. eyes. focus. you. always.",
     "him_mood": "coax"},
],
}


def pick_exchange(cat, used):
    """Pick one exchange for a category, bag semantics (no repeat until
    the category is exhausted). Returns (xid, exchange) or (None, None)."""
    pool = EXCHANGES.get(cat)
    if not pool:
        return None, None
    ids = [f"xchg_{cat}_{i}" for i in range(len(pool))
           if f"xchg_{cat}_{i}" not in used]
    if not ids:
        ids = [f"xchg_{cat}_{i}" for i in range(len(pool))]
    xid = random.choice(ids)
    idx = int(xid.rsplit("_", 1)[1])
    used.add(xid)
    return xid, pool[idx]
